spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zx-security?useUnicode=yes&characterEncode=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: none  #暂时关闭spring-session的配置，不然会报错
#security:
#  basic:
#    enabled: false #暂时关闭spring-security的配置，不然会报错



zx:
  security:
    browser:
      #配置登录方式
      loginType: JSON
    captcha:
      image:
        length: 4
      #配置自定义登录页
#      loginPage: /login.html
    social:
      qq:
        appId: wxd99431bbff8305a0
        appSecret: 60f78681d063590a469f1b297feff3c4
        providerId: qq
