server:
  port: 80
  session:
    timeout: 600
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zx-security?useUnicode=yes&characterEncode=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: NONE #可使用none,暂时关闭spring-session的配置
  redis:
    host: 106.14.7.29
    password: 123456
security:
  oauth2:
    client:
      client-id: zx
      client-secret: 123456
      access-token-validity-seconds:
  #  basic:
  #    enabled: false #可以暂时关闭spring-security的配置





zx:
  security:
    browser:
      login-type: json
      sign-up-url: /demo-signUp.html
    captcha:
      image:
        length: 4
      #配置自定义登录页
#      loginPage: /login.html
    social:
      #可自行配置的回调地址前缀,完整的回调地址是: 该url + "/" + providerId(服务提供商唯一标识)
      filterProcessesUrl: /oauth
      qq:
        appId: 101450725
        appSecret: 46bf4e9c8ecb8c36561c800181b8e7d4
        #服务提供商唯一标识, 此处为了适配不同的回调url,可做修改
        providerId: qq
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        provider-id: weixin
    oauth2:
      clients:
        - clientId: zx
          clientSecret: 123456
          accessTokenValiditySeconds: 100
          scopes:
            - all
            - read
            - write
      store-type: jwt
