server:
  port: 8080
  session:
    timeout: 600
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zx-security?useUnicode=yes&characterEncode=UTF-8&useSSL=false
    username: root
    password: 123456
  session:
    store-type: redis #可使用none,暂时关闭spring-session的配置
  redis:
    host: 106.14.7.29
    password: 123456
#security:
#  basic:
#    enabled: false #暂时关闭spring-security的配置，不然会报错



zx:
  security:
    browser:
      login-type: json
      sign-up-url: /demo-signUp.html
    captcha:
      image:
        length: 4
      #配置自定义登录页
#      loginPage: /login.html
    social:
      #可自行配置的回调地址前缀,完整的回调地址是: 该url + "/" + providerId(服务提供商唯一标识)
      filterProcessesUrl: /qqLogin
      qq:
        appId: 100550231
        appSecret: 69b6ab57b22f3c2fe6a6149274e3295e
        #服务提供商唯一标识, 此处为了适配不同的回调url,可做修改
        providerId: callback.do
      weixin:
        app-id: wxd99431bbff8305a0
        app-secret: 60f78681d063590a469f1b297feff3c4
        provider-id: weixin

